services:
  - type: web
    name: checklist-flet
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: FLET_STATIC_ROOT
        value: "."
